### ISSUE TITLE
ModuleNotFoundError: No module named 'captionsathome'

### ISSUE THREAD

**Issue by ywdong** [marianna13/translate_dataset#2]
Hi, thx your great job!
I have use the code to translate the text. But I got an error: 
  File "translate_data.py", line 13, in <module>
    import captionsathome as cah
ModuleNotFoundError: No module named 'captionsathome'

Can u help me with it?

**Comment by marianna13** [comment]
Hi! Thank you! You need to run the following command to clone captions at home lib:
`git clone --single-branch --branch caption-gen https://github.com/TheoCoombes/crawlingathome captionsathome`
